### ISSUE TITLE
typo: REQUIRED_TRANSACITON_KEYS

### ISSUE THREAD

**Issue by jperaire** [ethereum/eth-account#119]
There is a typo in

 eth_account/_utils/transactions.py

on lines 128, and 133. I'm not submitting a PR because I'm not sure if these may break something downstream.

**Comment by carver** [comment]
Looks like this got fixed:

https://github.com/ethereum/eth-account/blob/6e6e24c7d5f5ab916236fe4672f61aa184812f33/eth_account/_utils/legacy_transactions.py#L86

Please re-open if I misunderstood.
