### ISSUE TITLE
Ledger support

### ISSUE THREAD

**Issue by benjiqq** [ethereum/eth-account#123]
originally based on branch #34 I created ledgertools, a fully functional suite to interact with ledger. to merge back into eth-account some more work is needed. this library focuses on some extra security measures for signing which might be useful to add to eth-account.

https://github.com/vegaswap/ledgertools

**Comment by benjyz** [comment]
@carver made progress on this, any chance a maintainer can have a look at a PR when ready?

**Comment by carver** [comment]
Sure, someone should be able to do a quick review on a PR. Any feature like this would need an "unaudited flag" like the hdwallet implementation.

No one on our team is able to work on an implementation right now.

**Comment by pacrob** [comment]
Closing in favor of #25
