### ISSUE TITLE
EIP 1559 support ?

### ISSUE THREAD

**Issue by stolpa4** [ethereum/eth-account#124]
Hello, I see, you've included support for EIP-1559, however when I call Account.sign_transaction method I fell into the chain of functions: 
_utils.signing.sign_transaction_dict 
-->_utils.legacy_transactions.serializable_unsigned_transaction_from_dict 
--> assert_valid_fields. 

And it all ends with an error:  

TypeError: Transaction must include these fields: {'gasPrice'}.

How can I sign the new eip1559 transaction then? Do I need some other methods for eip1559 transactions?

EDIT:
Forgot to say, that I'm using the latest stable version: 0.5.5

**Comment by stolpa4** [comment]
Yep, I found, where I do wrong. It's not enough to just replace "gasPrice" with "maxPriorityFeePerGas" and "maxFeePerGas". I need to explicitly set the type also.

Thanks.

**Comment by kclowes** [comment]
Thanks for coming back and posting the solution! Much appreciated!
