### ISSUE TITLE
Investigate the need for bitarray dependency or update version

### ISSUE THREAD

**Issue by fselmo** [ethereum/eth-account#132]
### What was wrong?

- `bitarray` dependency seems to be the cause of many users not being able to install web3.py: 
- https://github.com/ethereum/web3.py/issues/1761
- https://github.com/ethereum/web3.py/issues/1788
- https://github.com/ethereum/web3.py/issues/2133
- https://github.com/ethereum/web3.py/issues/2147
- https://github.com/ethereum/web3.py/issues/2170
- https://github.com/ethereum/web3.py/issues/2171...

... and many cases on Discord

It seems to only be used in `hdaccount` support. We should investigate if we can remove this dependency while still supporting `hdaccount` logic.

### How can it be fixed?

1. Can we somehow remove `bitarray` dependency and keep `hdaccount` support?
2. Does updating the `bitarray` version resolve these issues?

I'm not confident in option `2` as I believe some users also tried to manually `pip install bitarray` and also had issues but I have not looked too far into this so I'll leave this option up.

**Comment by kclowes** [comment]
[This commit](https://github.com/ethereum/eth-account/commit/e2dc85921d1a97bef2568a09830ecc238a9bd5a6) is where it got added for reference.

**Comment by mebedel** [comment]
hey I found the solution 
SIMPLE WAY TO INSTALL WEB3
Install irudict , cytools from [https://www.lfd.uci.edu/~gohlke/pythonlibs/](https://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqbjY2QmU2WW9XZDZiMFFwc29BRGo3S0FyblVKd3xBQ3Jtc0tuNDF5WnVZTUh2RWdRT09FNGZtVDR3Z1hNSHNiZm9KMXVfTUtNanh1cVJzLUtXeHpEcXlTcElITjRSSnlZYmlRVE8xUVpoUmp6eW5hVVNaVjc0ZGg2dDZubFNZN3dFU1hENERiSWMyYmRydl9BUW81RQ&q=https%3A%2F%2Fwww.lfd.uci.edu%2F%7Egohlke%2Fpythonlibs%2F&stzid=UgwcMt1C-s_d8ZRRi8V4AaABAg)
watch this video [https://youtu.be/zbNczZLP1tA?t=348](https://www.youtube.com/watch?v=zbNczZLP1tA&t=348s)
if you don't know how to install from the wheels

Then paste:    pip install bitarray==1.2.2 to cmd
after that pip install web3

It should work without needing to install visual c build tools

**Comment by mebedel** [comment]
you just need to install bitarray==1.2.2 and it works

**Comment by mebedel** [comment]
please let me know if it works for others I invested quite a bit of time solving this.

**Comment by Kaditcuy** [comment]
> you just need to install bitarray==1.2.2 and it works
I tried this and it didn't work, then I tried the latest version of Bitarray 2.4.1, which also didn't work.

**Comment by Bruce95317** [comment]
tried the method mentioned above , still error 

Collecting bitarray==1.2.2
  Using cached bitarray-1.2.2.tar.gz (48 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: bitarray
  Building wheel for bitarray (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\bitarray
      copying bitarray\test_bitarray.py -> build\lib.win-amd64-3.8\bitarray
      copying bitarray\test_util.py -> build\lib.win-amd64-3.8\bitarray
      copying bitarray\util.py -> build\lib.win-amd64-3.8\bitarray
      copying bitarray\__init__.py -> build\lib.win-amd64-3.8\bitarray
      running build_ext
      building 'bitarray._bitarray' extension
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bitarray
  Running setup.py clean for bitarray
Failed to build bitarray
Installing collected packages: bitarray
  Running setup.py install for bitarray ... error
  error: subprocess-exited-with-error

  × Running setup.py install for bitarray did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\bitarray
      copying bitarray\test_bitarray.py -> build\lib.win-amd64-3.8\bitarray
      copying bitarray\test_util.py -> build\lib.win-amd64-3.8\bitarray
      copying bitarray\util.py -> build\lib.win-amd64-3.8\bitarray
      copying bitarray\__init__.py -> build\lib.win-amd64-3.8\bitarray
      running build_ext
      building 'bitarray._bitarray' extension
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> bitarray

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by mebedel** [comment]
I think I know what’s the problem 
First i installed  win c build tools 
Then checked bit array version used by web3 package 
afterwards I deleted win c build tools 
And did as mentioned by my first post 
I think that what got installed by the build tools didn’t get fully deleted 
I'll check more when I get to my pc

**Comment by Noob-A** [comment]
Still doesn't work

**Comment by fselmo** [comment]
Option 2 outlined here has been released on `v0.5.8` via #163 and will be released on `v.0.6.2` via #154.

**Comment by pietrodn** [comment]
Still waiting for the 0.6.2 release, this is forcing me to use a bigger Docker version with the GCC compiler.

**Comment by kclowes** [comment]
@pietrodn you should be able to use `0.5.8+` or `0.7.0`. We have a security fix that got released in 0.5.9 so I'd recommend using that or higher if you're on the `0.5.x` versions. I'm going to close this because I believe this should be fixed with the two releases mentioned above.

**Comment by pietrodn** [comment]
Unfortunately the `web3` library I'm using requires `eth-account >=0.6.0,<0.7.0` 😞

**Comment by kclowes** [comment]
@pietrodn out of curiosity, which library are you using?

**Comment by pietrodn** [comment]
@kclowes This one https://github.com/ethereum/web3.py

**Comment by kclowes** [comment]
@pietrodn what version?

**Comment by pietrodn** [comment]
6.0.0b4 (I need `asyncio` support)

**Comment by kclowes** [comment]
got it. I'm working on that now!
