### ISSUE TITLE
Omit venv dirs from sdist

### ISSUE THREAD

**Issue by hugovk** [ethereum/eth-account#150]
_If this is a bug report, please fill in the following sections.
If this is a feature request, delete and describe what you would like with examples._

### Code that produced the error

Download and extract the `eth-account-0.6.1.tar.gz` sdist:

https://pypi.org/project/eth-account/0.6.1/#files

And run `du -sh` on the directory and its contents.

### Full error output 

```console
$ du -sh /tmp/downloads/eth-account-0.6.1
 43M	/tmp/downloads/eth-account-0.6.1
$ du -sh /tmp/downloads/eth-account-0.6.1/*
4.0K	/tmp/downloads/eth-account-0.6.1/LICENSE
4.0K	/tmp/downloads/eth-account-0.6.1/MANIFEST.in
8.0K	/tmp/downloads/eth-account-0.6.1/PKG-INFO
4.0K	/tmp/downloads/eth-account-0.6.1/README.md
324K	/tmp/downloads/eth-account-0.6.1/eth_account
876K	/tmp/downloads/eth-account-0.6.1/eth_account.egg-info
4.0K	/tmp/downloads/eth-account-0.6.1/pyproject.toml
4.0K	/tmp/downloads/eth-account-0.6.1/requirements-docs.txt
4.0K	/tmp/downloads/eth-account-0.6.1/setup.cfg
4.0K	/tmp/downloads/eth-account-0.6.1/setup.py
 14M	/tmp/downloads/eth-account-0.6.1/venv-056
 14M	/tmp/downloads/eth-account-0.6.1/venv-ea-060
 14M	/tmp/downloads/eth-account-0.6.1/venv-ea-eabi
```

### Expected Result

```diff
 $ du -sh /tmp/downloads/eth-account-0.6.1
- 43M	/tmp/downloads/eth-account-0.6.1
+368K	/tmp/downloads/eth-account-0.6.1
 $ du -sh /tmp/downloads/eth-account-0.6.1/*
 4.0K	/tmp/downloads/eth-account-0.6.1/LICENSE
 4.0K	/tmp/downloads/eth-account-0.6.1/MANIFEST.in
 8.0K	/tmp/downloads/eth-account-0.6.1/PKG-INFO
 4.0K	/tmp/downloads/eth-account-0.6.1/README.md
 324K	/tmp/downloads/eth-account-0.6.1/eth_account
-876K	/tmp/downloads/eth-account-0.6.1/eth_account.egg-info
 4.0K	/tmp/downloads/eth-account-0.6.1/pyproject.toml
 4.0K	/tmp/downloads/eth-account-0.6.1/requirements-docs.txt
 4.0K	/tmp/downloads/eth-account-0.6.1/setup.cfg
 4.0K	/tmp/downloads/eth-account-0.6.1/setup.py
- 14M	/tmp/downloads/eth-account-0.6.1/venv-056
- 14M	/tmp/downloads/eth-account-0.6.1/venv-ea-060
- 14M	/tmp/downloads/eth-account-0.6.1/venv-ea-eabi
``` 

## How can it be fixed?

Omit the `venv*` directories (and `eth_account.egg-info`?) to reduce the contents from 43M to 368k.

They can be excluded by the `MANIFEST.in`.

Another suggestion is, when releasing, make a fresh clone of the repo and do it there (and document the release process, [for example](https://github.com/jmoiron/humanize/blob/master/RELEASING.md)).

See also https://github.com/ethereum/hexbytes/issues/17 and check your other packages :)

**Comment by kclowes** [comment]
Oops, thanks for the report! We do have our release process documented [here](https://github.com/ethereum/snake-charmers-tactical-manual/blob/master/cutting-a-release.md), but don't do a fresh clone of the repo every time.
