### ISSUE TITLE
sign-typed-data-v4  hope add support for arrays

### ISSUE THREAD

**Issue by ymmmmmmmm** [ethereum/eth-account#152]
hope add support for arrays thanks
 https://docs.metamask.io/guide/signing-data.html#sign-typed-data-v4
 https://medium.com/metamask/eip712-is-coming-what-to-expect-and-how-to-use-it-bb92fd1a7a26

**Comment by Fooyao** [comment]
hope add support for bytes

**Comment by pacrob** [comment]
Hi @ymmmmmmmm and @Fooyao  - take a look at PR #175 - it should fix your issue. If you get a chance, could you try your usecase against it and let us know if you're still seeing issues? Thanks!
