### ISSUE TITLE
Stricter eth-rlp dependency requirement

### ISSUE THREAD

**Issue by kclowes** [ethereum/eth-account#171]
## What was wrong?

The `eth-rlp` dependency is probably too broad right now. See [web3.py/#2502 ](https://github.com/ethereum/web3.py/pull/2502). Since it isn't out of the `0.x` releases, it can break on a minor release. 

## How can it be fixed?

Pin `eth-rlp` to the latest minor version. Currently, it would be `eth-rlp>=0.3.0,<0.4.0`. This is a breaking change, so we'll probably want to wait until we're ready to do a minor (breaking change) bump in`eth-account`.

**Comment by pacrob** [comment]
Closing as stale
