### ISSUE TITLE
EIP-712 Signatures generated by `eth-account` and `ether-js` are different when the message contains arrays

### ISSUE THREAD

**Issue by gqoew** [ethereum/eth-account#180]
## What was wrong?

Following issue #174, I noticed that signatures produced by `eth-account` are not matching ether-js's [`_signTypedData`](https://docs.ethers.io/v5/api/signer/#Signer-signTypedData)  for the example message with arrays [valid_eip712_example_with_array.json](https://github.com/ethereum/eth-account/blob/c35375a0f2441b6350df8fe5b57c22f1bcc8c52b/tests/fixtures/valid_eip712_example_with_array.json).

### Code that produced the error

Generate signature with `eth-account`:

```py
import os
import json
from eth_account.messages import encode_structured_data
from eth_account import Account

pk = os.environ['PRIVATE_KEY']

structured_msg = encode_structured_data(json.loads(open("valid_eip712_example_with_array.json", "r").read()))
signed = Account.sign_message(structured_msg, pk)
new_addr = Account.recover_message(structured_msg, signed.signature)
print(signed.signature.hex())
```

Generate signature with `ether-js`:

```js
const ethers = require('ethers')

var domainData =
  {
    "name": "Ether Mail",
    "version": "1",
    "chainId": 1,
    "verifyingContract": "0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC"
  }

var message = {
  "from": {
    "name": "Cow",
    "wallet": "0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826"
  },
  "to": {
    "name": "Bob",
    "wallet": "0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB"
  },
  "cc": [
    {
      "name": "Alice",
      "wallet": "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    },
    {
      "name": "Dot",
      "wallet": "0xdddddddddddddddddddddddddddddddddddddddd"
    }
  ],
  "contents": "Hello, Bob!"
}

var EIP_712_ORDER_TYPE = {
  "Person": [
    {"name": "name", "type": "string"},
    {"name": "wallet", "type": "address"}
  ],
  "Mail": [
    {"name": "from", "type": "Person"},
    {"name": "to", "type": "Person"},
    {"name": "cc", "type": "Person[]"},
    {"name": "contents", "type": "string"}
  ]
}

var signer = new ethers.Wallet(PRIVATE_KEY);

var signature = await signer._signTypedData(
  domainData,
  EIP_712_ORDER_TYPE,
  message
);

console.log(signature)
```

### Expected Result

I expected both signatures to match, like they did for the example [valid_eip712_example.json](https://github.com/ethereum/eth-account/blob/c35375a0f2441b6350df8fe5b57c22f1bcc8c52b/tests/fixtures/valid_eip712_example.json).

### Environment

```
eth-account==0.6.1
ethers/5.6.9
```

**Comment by kamilali** [comment]
+1 This seems to be an ongoing issue. Any chance that a change could be pushed to make this work? The signatures from web3js using _signTypedData and from web3py using encode_structured_data and sign_message are not the same. The JS one seems to be correct but the python version seems to have a bug. Referencing another issue that also talks about this on the OpenSea JS repo (https://github.com/ProjectOpenSea/opensea-js/issues/616).

**Comment by thywo** [comment]
Hi!

This issue is also blocking to me and it would be very helpful to have a fix.

Is there something we could do to help?

**Comment by thywo** [comment]
Great to hear!

Thank you for the update

**Comment by fselmo** [comment]
I think the PR is ready for some testing against it @gqoew. Couldn't hurt at this point to throw more test cases at it. There is still some more testing I want to do around acceptable nested tuple types against what Solidity accepts but if you want to run your cases against that branch, I believe is a good time to test it!

**Comment by gqoew** [comment]
@fselmo thank you for the update

Here's mine: I tried the reproducible example again and it worked! I will do further testing tomorrow with different payloads. Will keep you posted.
