### ISSUE TITLE
Default Scrypt parameters used by `Account.encrypt` are technically invalid.

### ISSUE THREAD

**Issue by akriegman** [ethereum/eth-account#181]
## What was wrong?

According to the Scrypt specification, the parameters of a keystore are supposed to satisfy `n < 2 ^ (128 * r / 8)`. The default parameters used by `eth_account.account.Account.encrypt` are `n = 262144, r = 1`, which violate this bound. I'm not sure what the reason is behind this bound, but I do know that the Rust package `scrypt.rs`, and it's dependents such as `ethers.rs`, return an error if you try to open a keystore that doesn't follow this bound.

Maybe someone else here knows why this bound is in the specification? My best guess is that if `n` is too big then the algorithm becomes proportionally more cpu-hard than memory-hard, but that's just a guess.

### Code that produced the error

```py
import json
import secrets
import sys

import eth_account

    key = secrets.token_hex(32)
    account = eth_account.account.Account.create()
    with open("wallet.json", "w") as f:
        wallet_file = json.dumps(
            eth_account.account.Account.encrypt(account.privateKey, key)
        )
        f.write(wallet_file)
    with open("wallet.pass", "w") as f:
        f.write(key)
```
Then, open the keystore with `ethers.rs`, or another Scrypt implementation which strictly follows the spec:
```rs
use ethers::prelude::*;
use std::fs::*;

fn main() -> Result<(), WalletError> {
  let _ = LocalWallet::decrypt_keystore(
    "wallet.json",
    read("wallet.pass")?,
  )?;
  Ok(())
}

```

### Full error output 

```sh
$ cargo run
Error: EthKeystoreError(ScryptInvalidParams(InvalidParams))
```

### Environment

```sh
$ python -m eth_utils
Python version:
3.9.2 (default, Jul 19 2022, 10:33:43) 
[GCC 9.4.0]

Operating System: Linux-5.15.0-41-generic-x86_64-with-glibc2.31

pip freeze result:
bitarray==1.2.2
cytoolz==0.12.0
eth-abi==3.0.1
eth-account==0.6.1
eth-hash==0.3.3
eth-keyfile==0.6.0
eth-keys==0.4.0
eth-rlp==0.3.0
eth-typing==3.1.0
eth-utils==2.0.0
hexbytes==0.2.2
parsimonious==0.8.1
pycryptodome==3.15.0
rlp==3.0.0
six==1.16.0
toolz==0.12.0
``` 

## How can it be fixed?

We would just have to turn down the default value of `n` from `2^18` to `2^15` or lower. I guess that alternatively we could raise `r` if people are worried that this would be too insecure? `r=1` seems to be pretty standard though.

**Comment by pacrob** [comment]
Thanks for bringing this up! I'm not sure why it was set where it is, but I'll take a look.

Reference for later:

Scrypt spec [here](https://www.rfc-editor.org/rfc/rfc7914#page-7)
Default `n` value set [here](https://github.com/ethereum/eth-keyfile/blob/3f26ae25e0ba11ee98ee3953417381d9f42db2e8/eth_keyfile/keyfile.py#L274)

**Comment by pacrob** [comment]
Per conversation (here)[https://github.com/golang/go/issues/33703#issuecomment-619951749], it's the RFC that is incorrect (note the errata filed). We likely got our value from (geth)[https://github.com/ethereum/go-ethereum/blob/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/accounts/keystore/testdata/v3_test_vector.json#L13].
