### ISSUE TITLE
EIP-712 Structured data identifiers

### ISSUE THREAD

**Issue by lgaroche** [ethereum/eth-account#190]
Hello,

is there a specific reason behind restricting the type identifier format for the eip-712 structured data validation (beyond the space character)? 
The identifier validation is here: 
https://github.com/ethereum/eth-account/blob/e6c3136bd30d2ec4738c2ca32329d2d119539f1a/eth_account/_utils/structured_data/validation.py#L8

I would like to sign and verify documents that will be published as an IPLD DAG object with links. Links are encoded as {"/": "<cid>"} in dag-cbor or dag-json.
The forward slash is rejected. This is allowed in ethers/metamask. 

Thank you!
Louis

**Comment by pacrob** [comment]
The [EIP](https://eips.ethereum.org/EIPS/eip-712#definition-of-typed-structured-data-%F0%9D%95%8A) notes that "these are closely related to Solidity types" and gives the definition as:

> A struct type has valid identifier as name and contains zero or more member variables. Member variables have a member type and a name.

And then [Solidity docs](https://docs.soliditylang.org/en/v0.8.16/grammar.html?highlight=0-9#a4.SolidityLexer.Identifier) give valid identifier names as they are defined in `eth-account`.

"Closely related" does not necessarily mean "exactly the same," but that's probably where the restriction came from.

**Comment by lgaroche** [comment]
Thanks for the clarification. I'll consider replacing the identifier with an alternate name just for the signature.
