### ISSUE TITLE
Implicit dependency on cytoolz (breaks PyPy)

### ISSUE THREAD

**Issue by oberstet** [ethereum/eth-account#215]
The library [depends](https://toolz.readthedocs.io/en/latest/api.html?highlight=dissoc#toolz.dicttoolz.dissoc) on `toolz.dicttoolz.dissoc`

https://github.com/ethereum/eth-account/blob/c5552a56b349e4c205089f50ddf54e942d4d9bc9/eth_account/account.py#L752

even though this requirement is *not* stated in the package setup

https://github.com/ethereum/eth-account/blob/c5552a56b349e4c205089f50ddf54e942d4d9bc9/setup.py#L67

This could be replaced with

```python
from copy import deepcopy
sanitized_transaction = deepcopy(transaction_dict)
sanitized_transaction.pop('from', None)
```

without introducing a dependency on cytoolz and allowing this library to be used on PyPy.

**Comment by kclowes** [comment]
closed via #251
