### ISSUE TITLE
DeprecationWarning: `encode_structured_data`

### ISSUE THREAD

**Issue by DvScripts** [ethereum/eth-account#243]
### What happened?

So i was using `encode_structured_data` and i received this ->

DeprecationWarning: `encode_structured_data` is deprecated and will be removed in a future release. Use encode_typed_data instead. So i changed it to -> `encode_typed_data` and i have error like this -> 

`structure_message = encode_typed_data(sign_structure)`

raise ValueError(f"Invalid domain key: `{k}`")

ValueError: Invalid domain key: 'domain`

**how to solve this ? I can add that with -> encode_structured_data it works correctly**

### eth-account Version

0.10.0

### Python Version

3.9.0

### Operating System

Windows

**Comment by pacrob** [comment]
The interface changed slightly from `encode_structured_data` to `encode_typed_data` to allow for different formats for the message data.

Short answer: `structure_message = encode_typed_data(full_message = sign_structure)` should do the trick. 

You can see updated docs with examples [here](https://eth-account.readthedocs.io/en/stable/eth_account.html#eth_account.messages.encode_typed_data). The method is new, feedback welcome!

**Comment by DvScripts** [comment]
Thank, that one helped.
