### ISSUE TITLE
eth-account depends on cytoolz

### ISSUE THREAD

**Issue by charles-cooper** [ethereum/eth-account#250]
it should be stated in the [project dependencies](https://github.com/ethereum/eth-account/blob/86b17a0a204f1d909dbf514ab6d754b939281017/setup.py#L50)

**Comment by kclowes** [comment]
Thank you for pointing this out. We actually should change those imports to be from `eth-utils` instead.

**Comment by charles-cooper** [comment]
this is maybe a dup of https://github.com/ethereum/eth-account/issues/215 btw
