### ISSUE TITLE
Default keyfile settings updated in eth-keyfile 0.7

### ISSUE THREAD

**Issue by sreyemnayr** [ethereum/eth-account#297]
The version is pinned to be >= 0.6.0, but when that version is used, wallets that depend on @noble/hashes for scrypt decryption throw errors about the keyfiles generated. Should be bumped to at least 0.7.0.
https://github.com/ethereum/eth-account/blob/aa55c07c338c25c1a9563046c4ce0a2111c4a325/setup.py#L55

https://github.com/paulmillr/noble-hashes/issues/61#issuecomment-2315618785

**Comment by fselmo** [comment]
Thanks for raising this @sreyemnayr. Looks like that's a good change to make. We'll get this in.

**Comment by kclowes** [comment]
This has been released in eth-account 0.13.3. Thanks for the report!
