### ISSUE TITLE
Allow specifying KDF function for `web3.eth.account.encrypt` API

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/eth-account#3]
Migrated from: https://github.com/ethereum/web3.py/issues/583

### What was wrong?

`eth-keyfile` supports passing in a `kdf` parameter to specify the key derivation function, but this api is not exposed via the `web3.eth.account.encrypt` API.

### How can it be fixed?

Add an optional keyword parameter `kdf` to allow specifying what KDF you want.

Extra options:

Allow setting the default KDF using both environment variables and via a property on the `web3.eth.account` module.

```python
web3.eth.account.defaultKDF = 'scrypt'
```

**Comment by pipermerriam** [comment]
> When you say allow providing of an environment variable, what exactly would you envision that as? Are we assuming it'll be some static key that the consumer would set in their env?

That means that *if* no KDF was specified and the environment variable `ETH_ACCOUNT_KDF` was set to the string `pbkdf2` then calling `Account.encrypt(pk, 'abc')` would produce a PBKDF2 encrypted keyfile.

> The environment variable name `ETH_ACCOUNT_KDF` was chosen arbitrarily by me.  If you have a better idea for the name :+1: (but namespacing it with `ETH_ACCOUNT` on the front of it is important.

**Comment by Misery42** [comment]
> ```
> >>> account.defaultKDF = 'pbkdf2'
> >>> account.defaultKDF
> 'pbkdf2'
> >>> pp.pprint(Account.encrypt(pk, 'abc'))
> {   'address': 'ac36b77275bcfb3bd0e760edaf90b18cf4ce9887',
>     'crypto': {   'cipher': 'aes-128-ctr',
>                   'cipherparams': {'iv': '0c1439b43e105e474fc50aaddeea180d'},
>                   'ciphertext': '6428099a3e72f2564f67d2c2f77296ed87110a21ce6ab37d5f028f48c016670e',
>                   'kdf': 'scrypt',
>                   'kdfparams': {   'dklen': 32,
>                                    'n': 262144,
>                                    'p': 8,
>                                    'r': 1,
>                                    'salt': '838f10c6d516d10bc6dfb3f663a59d3a'},
>                   'mac': 'a8a831e455fe94e84409779ae75d9bd220433c024d89e1e5d68597549399758e'},
>     'id': '23699d54-b3c4-4534-a211-8eee969fc330',
>     'version': 3}
> ```

Found a possible bug, at least it is incompatible with Web3.js and Ethers.
![image](https://github.com/ethereum/eth-account/assets/42983952/8e3caf9d-ef1a-4781-ae8a-46da75f437ed)
