### ISSUE TITLE
Accept bytes-type addresses in transactions

### ISSUE THREAD

**Issue by carver** [ethereum/eth-account#32]
## What was wrong?

If addresses are produced programatically, it is reasonable to skip the checksum check. There is no way to do this currently.

## How can it be fixed?

Accept native python `bytes` as a `to` address value, when signing a transaction. It must still be 20 bytes of course.

**Comment by pipermerriam** [comment]
marked with "Good First Issue" which may or may not be accurate.....

**Comment by stefanmendoza** [comment]
@carver @pipermerriam I'd like to try to tackle this 👍

**Comment by pipermerriam** [comment]
@stefanmendoza go for it!

**Comment by stefanmendoza** [comment]
@carver this can be closed 👍
