### ISSUE TITLE
Documentation not showing on readthedocs?

### ISSUE THREAD

**Issue by stefanmendoza** [ethereum/eth-account#39]
### Code that produced the error

When running the docs locally
```
$ make docs
```
I see the full documentation for methods and whatnot, but on readthedocs I don't see any of that?
https://eth-account.readthedocs.io/en/latest/eth_account.html

### Expected Result

Method and class doc shows up at the link above.

### Environment

```
Python version:
3.7.0 (default, Oct  2 2018, 09:18:58) 
[Clang 10.0.0 (clang-1000.11.45.2)]

Operating System: Darwin-18.0.0-x86_64-i386-64bit

pip freeze result:
alabaster==0.7.12
apipkg==1.5
appnope==0.1.0
argh==0.26.2
attrdict==2.0.0
attrs==18.2.0
Babel==2.6.0
backcall==0.1.0
bumpversion==0.5.3
certifi==2018.8.24
chardet==3.0.4
colorama==0.4.0
cytoolz==0.9.0.1
decorator==4.3.0
docopt==0.6.2
docutils==0.14
-e git+git@github.com:stefanmendoza/eth-account.git@adcd56cdeb4c65bd55c469c45ce78e2df1263a4d#egg=eth_account
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-typing==1.3.0
eth-utils==1.2.2
execnet==1.5.0
flake8==3.4.1
hexbytes==0.1.0
idna==2.7
imagesize==1.1.0
ipython==7.0.1
ipython-genutils==0.2.0
isort==4.3.4
jedi==0.13.1
Jinja2==2.10
MarkupSafe==1.0
mccabe==0.6.1
packaging==18.0
parso==0.3.1
pathtools==0.1.2
pexpect==4.6.0
pickleshare==0.7.5
pluggy==0.6.0
prompt-toolkit==2.0.6
ptyprocess==0.6.0
py==1.7.0
pycodestyle==2.3.1
pycryptodome==3.6.6
pyflakes==1.5.0
Pygments==2.2.0
pyparsing==2.2.2
pytest==3.3.2
pytest-forked==0.2
pytest-watch==4.2.0
pytest-xdist==1.23.2
pytz==2018.5
PyYAML==3.13
requests==2.19.1
rlp==1.0.3
simplegeneric==0.8.1
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.8.1
sphinx-rtd-theme==0.4.2
sphinxcontrib-websupport==1.1.0
toolz==0.9.0
tox==2.9.1
traitlets==4.3.2
urllib3==1.23
virtualenv==16.0.0
watchdog==0.9.0
wcwidth==0.1.7
```

## How can it be fixed?

N/A

**Comment by stefanmendoza** [comment]
Published docs:
<img width="1279" alt="screen shot 2018-10-14 at 11 39 46 am" src="https://user-images.githubusercontent.com/6325996/46919511-0af2b880-cfa6-11e8-8c72-c9d8f1a5ba60.png">

Local docs:
<img width="1280" alt="screen shot 2018-10-14 at 11 39 56 am" src="https://user-images.githubusercontent.com/6325996/46919522-1645e400-cfa6-11e8-9867-e739a95ebf54.png">

**Comment by carver** [comment]
Looks like eth-utils is using some py3.6 syntax. I'm investigating why that didn't fail in CI tests on py35.

**Comment by carver** [comment]
This :boom:ing thing again: https://github.com/ethereum/web3.py/issues/1012#issuecomment-415183759

RTD must be using py3.5.2 as the default py3

**Comment by pipermerriam** [comment]
Looks like we may be able to update to use the latest 3.0 builder: which uses 3.5.4

https://docs.readthedocs.io/en/latest/builds.html#latest

**Comment by pipermerriam** [comment]
https://docs.readthedocs.io/en/latest/yaml-config.html#build-image

**Comment by pipermerriam** [comment]
Which also looks like it has better support for how we specify our documentation dependencies.

https://docs.readthedocs.io/en/latest/yaml-config.html#python-extra-requirements

**Comment by pipermerriam** [comment]
Sorry, should have posted the "more details" link:  https://github.com/rtfd/readthedocs-docker-images/blob/releases/3.x/Dockerfile
