### ISSUE TITLE
Account.create() pbkdf2 iterations/work-factor access

### ISSUE THREAD

**Issue by AndreMiras** [ethereum/eth-account#48]
[Account.encrypt()](https://github.com/ethereum/eth-account/blob/8cb7d4e/eth_account/account.py#L137) doesn't provide means to set the `iterations` (work-factor) parameter of the [eth_keyfile.keyfile.create_keyfile_json()](https://github.com/ethereum/eth-keyfile/blob/v0.5.1/eth_keyfile/keyfile.py#L37) method.
It would be useful if that was somewhat possible without monkey patching the call.
My use case is I'm running Python-based "Ethereum clients" on smart-phones (e.g. [EtherollApp](https://github.com/AndreMiras/EtherollApp), [PyWallet](https://github.com/AndreMiras/PyWallet)) and it has less resources so account creation with default pbkdf2 params may take ages.
I was initially using [pyethereum](https://github.com/ethereum/pyethereum) where it was somewhat possible overriding `PBKDF2_CONSTANTS['c']`, but I'm in the process of migrating it since it's deprecated.

They way around I'm currently using with `eth-account` is to monkey patch `create_keyfile_json()` call.
```python
import eth_account
from eth_keyfile import create_keyfile_json

account = eth_account.Account.create()
eth_account.account.create_keyfile_json = partial(
    create_keyfile_json, iterations=1)
encrypted = eth_account.Account.encrypt(account.privateKey, "password")
```
I know setting `iterations=1` is terribly wrong but it's for demo-purpose. It could be useful for speeding up unit testing too.

Anyway, if the use-case of giving access to this param makes sense, I could make a pull request.

**Comment by pipermerriam** [comment]
I'm :+1: on figuring out a way to allow these parameters to be explicitly set.

**Comment by stefanmendoza** [comment]
@AndreMiras I put out a PR for this:
https://github.com/ethereum/eth-account/pull/52

Feel free to check it out and let me know what you think! 👍

**Comment by AndreMiras** [comment]
I eventually updated to recent `eth-account` and I confirm this is working OK, I can take out my monkey patch, thanks :smile:
