### ISSUE TITLE
Case sensitive error when signing tx

### ISSUE THREAD

**Issue by pastet89** [ethereum/eth-account#50]
When I call w3.eth.account.signTransaction(tx, key)

I am getting the following error:

`TypeError: from field must match key's 0xe6fAfd26257963055c93fc8a38Dd4554BB157349, but it was 0xe6fafd26257963055c93fc8a38dd4554bb157349`

Obviously the key converts to the right address, but some of the letters are caps while some are not. What can I do about it?

**Comment by pastet89** [comment]
Edit: I realised I am passing lowcase address as a param to the function. Seems like the bancor API is returning it this way.

**Comment by carver** [comment]
Yup, I'd highly recommend that bancor start showing [eip-55 checksum addresses](https://eips.ethereum.org/EIPS/eip-55).
