### ISSUE TITLE
How to use eth-account lib to send a token ERC20 to other address

### ISSUE THREAD

**Issue by henrytom1703** [ethereum/eth-account#51]
_If this is a bug report, please fill in the following sections.
If this is a feature request, delete and describe what you would like with examples._

### Code that produced the error

```py
CODE_TO_REPRODUCE 
```

### Full error output 

```sh
ERROR_HERE 
```

### Expected Result

_This section may be deleted if the expectation is "don't crash"._

```sh
EXPECTED_RESULT
``` 

### Environment

```sh
# run this:
$ python -m eth_utils

# then copy the output here:
OUTPUT_HERE
``` 

## How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by carver** [comment]
Since this isn't a bug or feature request for Web3.py, I'm closing the issue. One alternative to consider is https://ethereum.stackexchange.com

You will get better & faster answers if your question has a minimal, complete, and verifiable example: https://stackoverflow.com/help/mcve
