### ISSUE TITLE
Replace is_valid_abi_type with ABI's is_encodable_type method

### ISSUE THREAD

**Issue by Bhargavasomu** [ethereum/eth-account#59]
## What was wrong?
Currently `eth-account` is still supporting `python 3.5`. But to replace utils method `is_valid_abi_type` with ABI's method `is_encodable_type`, it is possible only when the support of `python 3.5` is removed by `eth-account`, because `eth-abi` currently doesn't support `python 3.5`

## How can it be fixed?

Replace the function, when the support for `python 3.5` is dropped in `eth-account`.

**Comment by Bhargavasomu** [comment]
Further details related to this issue can be found [here](https://github.com/ethereum/eth-account/pull/57#issuecomment-478207050)

**Comment by carver** [comment]
Closed by #67
