### ISSUE TITLE
deprecate camelCase for snake_case

### ISSUE THREAD

**Issue by carver** [ethereum/eth-account#62]
Add `snake_case` options for all public APIs. Raise warnings and add notes to all the other methods, to indicate they are deprecated. This minor (breaking) bump to v0.4 will introduce the deprecation. The next minor (breaking) bump to v0.5 will remove all camelCase methods.

**Comment by carver** [comment]
Mostly closed by #64 but there are some attributes/keys left on the returned values (like `messageHash` in `sign_message()`).

First noted in https://github.com/ethereum/web3.py/pull/1348#issuecomment-489744940

**Comment by kclowes** [comment]
Completed via #268
