### ISSUE TITLE
EIP712Domain fields shouldn't all be required

### ISSUE THREAD

**Issue by wbobeirne** [ethereum/eth-account#72]
This bit of validation: https://github.com/ethereum/eth-account/blob/32f98c86ada6b1a192633ba48d3f77ec19e55b3f/eth_account/_utils/structured_data/validation.py#L58-L80 requires that all EIP712Domain fields be provided or the library raises an exception. However the [EIP-712 spec says on EIP712Domain](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md#definition-of-domainseparator) that any one of these should be able to be omitted:

> where the type of eip712Domain is a struct named EIP712Domain with one or more of the below fields. Protocol designers only need to include the fields that make sense for their signing domain. Unused fields are left out of the struct type.

**Comment by jstoxrocky** [comment]
This got no traction in the past few months but I also agree. Although you should probably fill out all the suggested fields, they should not be required.

**Comment by fubuloubu** [comment]
Fixed in #112

**Comment by fselmo** [comment]
closed by #112
