### ISSUE TITLE
Release version with correct eth-keys dependency

### ISSUE THREAD

**Issue by niklasb** [ethereum/eth-account#75]
## What was wrong?

Version 0.4.0 as released on PyPI has a dependency on eth-keys<0.3.0. However, eth-keys is now available in version 0.3.1, and some other Ethereum-related packages depend on >=0.3.0.

### Expected Result

eth-keys should depend on eth-keys<0.4.0, as is currently the case in the master branch.

## How can it be fixed?

Probably by bumping the eth-account version to 0.4.1 and updating the dependency

**Comment by AndreMiras** [comment]
Fixed in master via https://github.com/ethereum/eth-account/pull/69 but not yet released in PyPI

**Comment by niklasb** [comment]
Seeing as this is almost half a year old, when can we expect a new release?

**Comment by kclowes** [comment]
Closed via #69
