### ISSUE TITLE
Support for HD and Mnemonic key derivation.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/eth-account#8]
* Tools like metamask use [mnemonic passphrases](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) for key backups.
* [HD wallets](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) are a widely used thing.

Supporting these types of accounts/wallets would likely be a useful feature.

> Note that I'm not sure whether metamask uses bip39 style mnemonics so we should look into that.

**Comment by carver** [comment]
https://github.com/trezor/python-mnemonic could be a useful reference (linked from the bip39 doc). It doesn't appear to do HD wallets, though.

**Comment by pipermerriam** [comment]
Browsing the code, we probably want to look into lifting our own implementation with that one as a guide.  I see at least one spot where I think their code is broken:

https://github.com/trezor/python-mnemonic/blob/master/mnemonic/shamir.py#L69  Looks like the same issue we ran into at some point with hex encoding integer values which are really representative of fixed length byte values where the resulting hex representation ends up missing some leading zeros.  (not 100% sure I'm right).

**Comment by pipermerriam** [comment]
Specific issue for HD wallets here: https://github.com/ethereum/eth-account/issues/24
