### ISSUE TITLE
signHash is deprecated in favor of sign_message

### ISSUE THREAD

**Issue by Uxio0** [ethereum/eth-account#85]
After I updated to the last version of `eth-account` I see this warning on my tests. At first I thought it would be just renaming the function, but I realized I cannot sign a custom hash anymore. I understand this can be a way of preventing users to sign hashes of transactions by mistake, but I think a developer should have the possibility of signing hashes and in my case I need it for some contracts that rely on signing hashes and not messages.

## How can it be fixed?

I would propose not deprecating the old method or adding a raw `SignableMessage` that allows to sign hashes.

It could be possible that there's a way to do it and I didn't figure it out, sorry if that's the case

**Comment by pipermerriam** [comment]
I believe you can still do it using a combination of  [`encode_defunct`](https://eth-account.readthedocs.io/en/stable/eth_account.html#eth_account.messages.encode_defunct) -> [`sign_message`](https://eth-account.readthedocs.io/en/stable/eth_account.html#eth_account.account.Account.sign_message)

**Comment by pipermerriam** [comment]
Looking at it I think you are correct that we've removed the ability to sign an arbitrary hash.

cc @carver

**Comment by carver** [comment]
It's important to not to make it too easy to trick someone into signing a transaction. That's the premise behind only supporting the EIP-191 message format: https://eth-account.readthedocs.io/en/stable/eth_account.html#eth_account.messages.SignableMessage 

You'll notice that clients typically do the same thing: there is no way to send an arbitrary hash to be signed over json-rpc.

It's not hard to imagine a malicious contract deployer who constructs the contract so that you sign some arbitrary hash which lets them transfer all the funds out of your account. That's only one reason why it's a really bad idea to sign a hash you don't have the preimage for.

There are ways to sign arbitrary hashes using eth-keys, so it's not literally impossible, if you absolutely must go that route. The best solution, though, would be to get the contract operator to switch to some variant of the EIP-191 standard.

**Comment by pipermerriam** [comment]
I'm going to close this as wontfix, but if you need help understanding any of the `eth-keys` APIs (they  are pretty simple so try the documentation first) feel free to open an issue:

https://github.com/ethereum/eth-keys

Documentation is there in the README

**Comment by Uxio0** [comment]
> It's important to not to make it too easy to trick someone into signing a transaction. That's the premise behind only supporting the EIP-191 message format: https://eth-account.readthedocs.io/en/stable/eth_account.html#eth_account.messages.SignableMessage

**Comment by Uxio0** [comment]
> It's important to not to make it too easy to trick someone into signing a transaction. That's the premise behind only supporting the EIP-191 message format: https://eth-account.readthedocs.io/en/stable/eth_account.html#eth_account.messages.SignableMessage

Agree, but this is not a UI, I'm developing an application. I decide what to sign, and as you say, I have a lot of ways to trick the user. I don't get the point of making things harder for developers.

> You'll notice that clients typically do the same thing: there is no way to send an arbitrary hash to be signed over json-rpc.

Agree, but this is not an HTTP service exposing methods, this is a core library for Python to manage ethereum accounts.

> The best solution, though, would be to get the contract operator to switch to some variant of the EIP-191 standard.

As you know is not easy to do so :wink:

> There are ways to sign arbitrary hashes using eth-keys, so it's not literally impossible, if you absolutely must go that route

I know I can use another libraries, but it was really convenient to use `eth-account` for all that.

From my humble opinion this change feels like removing MD5 from a cryptography library because using it is not secure for the user and everyone should upgrade to SHA256. I think the developer must know what is doing and shouldn't have this kind of "protection". As you say, I can just use another library to get it working to trick the user.

But it's your library and your call :smiley:, thanks for your time and the recommendation of using `eth-keys`, I haven't used that library and looks very powerful

**Comment by pipermerriam** [comment]
@Uxio0 thanks for posting.  After reading this I'm more on the fence about our decision.  I'd be curious to understand whether you're able to do what you need to do with `eth-keys` and if you are not, to understand what problems you encountered.

A potential solution here would be to improve our documentation to include a section on signing arbitrary hashes, why it has been excluded from the library and ensure the eth-keys documentation is adequate to help people who need this use case easily do it correctly.

**Comment by Uxio0** [comment]
> @Uxio0 thanks for posting. After reading this I'm more on the fence about our decision. I'd be curious to understand whether you're able to do what you need to do with `eth-keys` and if you are not, to understand what problems you encountered.

Digging more into the code, I see that I can just call `_sign_hash`, even if it's supposed to be private. The new `sign_message` depends on it so it doesn't seem it will be removed.

I have been reading the documentation for `eth-keys` and it looks really straightforward too if I need to use it.

> A potential solution here would be to improve our documentation to include a section on signing arbitrary hashes, why it has been excluded from the library and ensure the eth-keys documentation is adequate to help people who need this use case easily do it correctly.

Agree, as I think is a common issue and even if the desirable is working with EIP-191 or EIP-712 messages that's not how a lot of contracts work than still need support (like old Gnosis Safe version v0.0.1 or Gnosis Multisig). I guess is just me complaining because it's just a warning and the method can still be used.

**Comment by pipermerriam** [comment]
Here's where I *think* I stand on this after thinking on it for a week.

```python
account = ...
message_hash = user_function_to_compute_message_hash(...)
signature = account.sign_raw_message_hash(message_hash)
```

This is basically just bringing back `account.signHash`.  I don't necessarily feel strongly that this is the right thing to do, but I'm not sure that our argument about "tricking* people into signing bad things holds water since our audience is developers...

**Comment by Uxio0** [comment]
> This is basically just bringing back `account.signHash`. I don't necessarily feel strongly that this is the right thing to do, but I'm not sure that our argument about "tricking* people into signing bad things holds water since our audience is developers...

Totally agree on that solution

**Comment by carver** [comment]
> I'm not sure that our argument about "tricking* people into signing bad things holds water since our audience is developers...

I don't want to lean too hard on past decisions out of context, but someone (I think in the go-ethereum team) made the same decision to keep bare hash signing out of json-rpc, which also seems to be a developer audience.

The thing is that we already decided to support the capability via eth-keys. They were actually *preventing* signing an unknown hash. So we're just deciding how much friction we want to artificially add in to help people from hurting themselves. (or most likely from writing tools that hurt other people unintentionally)

---

Out of curiosity, for your use cases @Uxio0 do you know the preimage? One thing we could do is to sign a raw message where you pass in the pre-image instead of passing in the hash. Then we could check if the pre-image looks like a transaction. It's a little annoying to add a security-critical maintenance task (as the transaction format can change over time). But if it's really important for us to support this, then the added maintenance cost is better than encouraging the blind signing of unknown preimages.

**Comment by Uxio0** [comment]
> I don't want to lean too hard on past decisions out of context, but someone (I think in the go-ethereum team) made the same decision to keep bare hash signing out of json-rpc, which also seems to be a developer audience.

I disagree, it's not the same a `json-rpc` and the security required for a server than a programming language library. E.g. in a server you don't provide endpoints to retrieve plain text passwords (or you don't even store them), but the libraries need to support plain text passwords.

> The thing is that we already decided to support the capability via eth-keys. They were actually _preventing_ signing an unknown hash. So we're just deciding how much friction we want to artificially add in to help people from hurting themselves. (or most likely from writing tools that hurt other people unintentionally)

I guess that's responsability of the coder, to read the documentation and know what the tools are doing. But if you decide to go that path, I don't have any problem on using `eth-keys`.
 
> Out of curiosity, for your use cases @Uxio0 do you know the preimage? One thing we could do is to sign a raw message where you pass in the pre-image instead of passing in the hash. Then we could check if the pre-image looks like a transaction. It's a little annoying to add a security-critical maintenance task (as the transaction format can change over time). But if it's really important for us to support this, then the added maintenance cost is better than encouraging the blind signing of unknown preimages.

I don't know the preimage in some cases.

**Comment by carver** [comment]
> > Out of curiosity, for your use cases @Uxio0 do you know the preimage? One thing we could do is to sign a raw message where you pass in the pre-image instead of passing in the hash. Then we could check if the pre-image looks like a transaction. It's a little annoying to add a security-critical maintenance task (as the transaction format can change over time). But if it's really important for us to support this, then the added maintenance cost is better than encouraging the blind signing of unknown preimages.
> 
> I don't know the preimage in some cases.

Can you give an example or two? (I'm trying to see if there's another way we can support it. Alternatively, if we do decide to support it directly, we should probably list example scenarios in the docs of when you might be forced to do something so dangerous)

**Comment by Uxio0** [comment]
> Can you give an example or two? (I'm trying to see if there's another way we can support it. Alternatively, if we do decide to support it directly, we should probably list example scenarios in the docs of when you might be forced to do something so dangerous)

Of course :) . For example:
- Using a multisig wallet, like GnosisSafe, and then you see another owners you trust sign a hash to execute a tx, you just see the hash but decide to sign it as you trust the other owners that approved first. Some owner accounts do not hold any funds so no problem of signing a tx by mistake. https://github.com/gnosis/safe-contracts/blob/development/contracts/GnosisSafe.sol#L290
- Future (or existing) contracts/dapps using different type of signatures not complaint with eip-191

Don't worry about this subject, I just brought it out because at first I thought you were not doing it on purpose and it was just a mistake that signing a hash was let out. What you decide will be ok with me and I will find a way to implement the use cases I need :)

**Comment by antazoey** [comment]
It has been years.=
`eth-account` is on version 0.12.1. The deprecation message _still_ says it will be removed in 0.6.
As outlined in this issue, there are still use-cases requiring it.

**Can something happen?**
